### ISSUE TITLE
Crear prototipo Mobile en Figma

### ISSUE THREAD

**Issue by ingridgallegosp** [Sharonina/DEV002-social-network#7]
- [x] Crear Figma
- [x] Unir todas las participantes al Figma
- [x] Terminar el prototipo
- [x] Añadir interacción

**Comment by Sharonina** [comment]
Prototipo de interacción:
https://www.figma.com/proto/Jdz2la2rY8uAYWeGdJZohF/Untitled?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2
